#ifndef WATERARMY_MAIN_WATERARMY_LIB_MOCK_SENSORFUNCTIONS_H_
#define WATERARMY_MAIN_WATERARMY_LIB_MOCK_SENSORFUNCTIONS_H_

#include "gmock/gmock.h"
#include "gmock-global/gmock-global.h"

MOCK_GLOBAL_FUNC1(readSensor, long(const long));

#endif //WATERARMY_MAIN_WATERARMY_LIB_MOCK_SENSORFUNCTIONS_H_