//
// Created by jaume on 11/13/19.
//

#ifndef WATERARMY_MAIN_WATERARMY_LIB_WATERINGFUNCTIONS_H_
#define WATERARMY_MAIN_WATERARMY_LIB_WATERINGFUNCTIONS_H_

long readInputById(long readerId);

#endif //WATERARMY_MAIN_WATERARMY_LIB_WATERINGFUNCTIONS_H_
